name: Node.js CI

on:
  push:
    branches: [ main, develop ]
  workflow_dispatch: {}

defaults:
  run:
    working-directory: backend

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix: { node-version: [14.x] }

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: { node-version: ${{ matrix.node-version }} }
      - run: npm ci
      - run: npm run build --if-present
      # - run: npm test                     # <— disabilitato
      - name: Skip tests
        run: echo "No tests to run"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    environment: production
    env:
      RENDER_TOKEN:     ${{ secrets.RENDER_TOKEN }}
      SERVICE_ID:       ${{ secrets.RENDER_SERVICE_ID }}
    steps:
      - uses: actions/checkout@v3
      - name: Trigger deploy su Render
        uses: bounceapp/render-action@0.6.0
        with:
          render-token: ${{ env.RENDER_TOKEN }}
          service-id:   ${{ env.SERVICE_ID }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          retries: 20
          wait:    16000
          sleep:   30000
