name: CI & Deploy BeTN

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest

    # Ogni run() di seguito verrà eseguito in `backend/`
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      - name: Install dependencies
        # qui ci assicuriamo che backend/package.json + package-lock.json vengano letti
        run: npm ci

      - name: Build (if-needed)
        run: npm run build --if-present

      - name: Skip tests (no script defined)
        run: echo "Skipping tests"

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Trigger deploy su Render
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        uses: bounceapp/render-action@0.6.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          render-token:  ${{ secrets.RENDER_TOKEN }}
          service-id:    ${{ secrets.RENDER_SERVICE_ID }}
          retries: 20
          wait:    16000
          sleep:   30000
