name: CI & Deploy BeTN

# Partiamo sia su push (main/develop) sia con "Run workflow"
on:
  push:
    branches:
      - develop
  workflow_dispatch: {}

# Tutti i comandi npm girano in backend/
defaults:
  run:
    working-directory: backend

# Inietto qui in alto tutte le env var del backend
env:
  DB_HOST:    ${{ secrets.DB_HOST }}
  DB_NAME:    ${{ secrets.DB_NAME }}
  DB_USER:    ${{ secrets.DB_USER }}
  DB_PASS:    ${{ secrets.DB_PASS }}
  HOST:       ${{ secrets.HOST }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  PORT:       ${{ secrets.PORT }}

jobs:
  test:
    name: Test & Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build (if-needed)
        run: npm run build --if-present

      - name: Skip tests (no script defined
        run: echo "Skipping tests"

  deploy:
    name: Deploy to Render
    needs: test
    runs-on: ubuntu-latest
    # se vuoi puoi specificare qui environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Trigger deploy on Render
        if: github.event_name == 'push' || github.event_name == 'pull_request'
        uses: bounceapp/render-action@0.6.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          render-token:  ${{ secrets.RENDER_TOKEN }}
          service-id:    ${{ secrets.RENDER_SERVICE_ID }}
          retries: 20
          wait:    16000
          sleep:   30000
