name: Node.js CI

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch: {}

defaults:
  run:
    working-directory: backend

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - name: Smoke test working-directory
        run: |
          echo "Current dir: $(pwd)"
          ls -la

      - name: Dummy test
        run: |
          echo "Everything OK"
          exit 0

  deploy:
    needs: test
    runs-on: ubuntu-latest
    environment: production
    env:
      RENDER_TOKEN: ${{ secrets.RENDER_TOKEN }}
      SERVICE_ID:   ${{ secrets.RENDER_SERVICE_ID }}
    steps:
      - uses: actions/checkout@v3

      - name: Trigger deploy su Render
        if: github.event_name == 'push'
        uses: bounceapp/render-action@0.6.0
        with:
          render-token: ${{ env.RENDER_TOKEN }}
          service-id:   ${{ env.SERVICE_ID }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          retries: 20
          wait:    16000
          sleep:   30000
